In [1]:
import pandas as pd

In [3]:
df = pd.read_csv("Trendix_Dataset.csv")
df

,Serial_No,Fashion_type,Product_id,Brand_Name,category,Description,Rating,Rating_count,Price,MRP_Price,Discount,size,product_description,image_ref,file_path,image_url,Specifications,Rating_as_stars
0,1,blazers,17464542.0,H&M,women-clothing,Women Black Fitted Jacket,4.4,951Ratings,MRP₹ 2299,MRP,NaN,"['XXS', 'XS', 'S', 'M', 'L', 'XL', 'XXL', '3XL']",Fitted jacket in woven fabric with notch lapel...,blazers_women-clothing_17464542.jpg,C:/Users/harsh/OneDrive/Desktop/AI & DS/Step 2...,"https://assets.myntassets.com/h_720,q_90,w_540...","{'Closure': 'Button', 'Collar': 'Notched Lapel...","{'5': '645', '4': '176', '3': '62', '2': '27',..."
1,2,blazers,24970972.0,Allen Solly Woman,women-clothing,Notched Lapel Collar Single-Breasted Formal Bl...,4.3,643Ratings,₹3959,MRP₹3999,(1% OFF),NaN,"Black solid regular-fit formal blazer, has a n...",blazers_women-clothing_24970972.jpg,C:/Users/harsh/OneDrive/Desktop/AI & DS/Step 2...,"https://assets.myntassets.com/h_720,q_90,w_540...","{'Closure': 'Button', 'Collar': 'Notched Lapel...","{'5': '421', '4': '113', '3': '29', '2': '21',..."
2,3,blazers,26893598.0,Arrow,men-clothing,Notched Lapel Long Sleeves Slim-Fit Single Bre...,4.2,161Ratings,₹4879,MRP₹7999,(39% OFF),"['36', '38', '40', '42', '44', '46']","Black solid slim-fit formal blazer, has a notc...",blazers_men-clothing_26893598.jpg,C:/Users/harsh/OneDrive/Desktop/AI & DS/Step 2...,"https://assets.myntassets.com/h_720,q_90,w_540...","{'Closure': 'Button', 'Collar': 'Notched Lapel...","{'5': '98', '4': '29', '3': '11', '2': '9', '1..."
3,4,blazers,28844176.0,MANGO,women-clothing,Pure Linen Smart Casual Blazer,4.1,37Ratings,MRP₹ 6790,MRP,NaN,"['XXS', 'XS', 'S', 'M', 'L', 'XL', 'XXL']","Blue solid smart casual blazer, has a peaked l...",blazers_women-clothing_28844176.jpg,C:/Users/harsh/OneDrive/Desktop/AI & DS/Step 2...,"https://assets.myntassets.com/h_720,q_90,w_540...","{'Closure': 'Button', 'Collar': 'Peaked Lapel'...","{'5': '26', '4': '2', '3': '1', '2': '2', '1':..."
4,5,blazers,28774520.0,MANGO,women-clothing,Smart Casual Linen Notched Lapel Single-Breast...,4.0,43Ratings,₹4549,MRP₹6790,(33% OFF),"['XS', 'S', 'M', 'L', 'XL', 'XXL']","The solid blazers for women, has notched lapel...",blazers_women-clothing_28774520.jpg,C:/Users/harsh/OneDrive/Desktop/AI & DS/Step 2...,"https://assets.myntassets.com/h_720,q_90,w_540...","{'Closure': 'Button', 'Collar': 'Notched Lapel...","{'5': '30', '4': '2', '3': '1', '2': '3', '1':..."
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
24173,994,Women Office Wear,30111247.0,Style Quotient,women-clothing,Women Smart Opaque Formal Shirt,4.0,6Ratings,₹636,MRP₹1299,(51% OFF),"['S', 'M', 'L', 'XL']","White solid opaque Formal shirt ,has a spread ...",Women Office Wear_women-clothing_30111247.jpg,C:/Users/DELL/OneDrive/Desktop/AI & DATA SCIEN...,"https://assets.myntassets.com/h_720,q_90,w_540...","{'Sleeve Length': 'Short Sleeves', 'Collar': '...","{'5': '3', '4': '1', '3': '1', '2': '1', '1': ''}"
24174,995,Women Office Wear,27631984.0,Chemistry,women-clothing,Striped Formal Shirt,4.2,43Ratings,₹499,MRP₹1999,(75% OFF),"['XS', 'S', 'M', 'XL', 'L']",Black & white vertical striped opaque formal s...,Women Office Wear_women-clothing_27631984.jpg,C:/Users/DELL/OneDrive/Desktop/AI & DATA SCIEN...,"https://assets.myntassets.com/h_720,q_90,w_540...","{'Sleeve Length': 'Long Sleeves', 'Collar': 'S...","{'5': '24', '4': '11', '3': '5', '2': '', '1':..."
24175,996,Women Office Wear,29328582.0,Annabelle by Pantaloons,women-clothing,Women Opaque Formal Shirt,4.6,22Ratings,MRP₹ 1499,MRP,NaN,"['XS', 'S', 'M', 'L', 'XL', 'XXL']","Blue solid opaque Formal shirt ,has a spread c...",Women Office Wear_women-clothing_29328582.jpg,C:/Users/DELL/OneDrive/Desktop/AI & DATA SCIEN...,"https://assets.myntassets.com/h_720,q_90,w_540...","{'Sleeve Length': 'Long Sleeves', 'Collar': 'S...","{'5': '16', '4': '3', '3': '3', '2': '', '1': ''}"
24176,997,Women Office Wear,29173318.0,Cantabil,women-clothing,Spread Collar Formal Shirt,4.4,31Ratings,₹899,MRP₹1999,(55% OFF),"['S', 'M', 'L', 'XL', 'XXL', '3XL']","Green solid opaque Formal shirt ,has a spread ...",Women Office Wear_women-clothing_29173318.jpg,C:/Users/DELL/OneDrive/Desktop/AI & DATA SCIEN...,"https://assets.myntassets.com/h_720,q_90,w_540...","{'Sleeve Length': 'Long Sleeves', 'Collar': 'S...","{'5': '21', '4': '7', '3': '', '2': '', '1': '3'}"
24177,998,Women Office Wear,28324258.0,FITHUB,women-clothing,Women Slim Fit High-Rise Formal Trousers,3.8,55Ratings,₹899,MRP₹1999,(55% OFF),"['30', '32', '34', '36', '38', '40', '42']",Fit: Slim FitThe model (height 5'8) is wearing...,Women Office Wear_women-clothing_28324258.jpg,C:/Users/DELL/OneDrive/Desktop/AI & DATA SCIEN...,"https://assets.myntassets.com/h_720,q_90,w_540...","{'Waist Rise': 'High-Rise', 'Length': 'Regular...","{'5': '28', '4': '9', '3': '6', '2': '2', '1':..."

In [5]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 24178 entries, 0 to 24177
Data columns (total 18 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   Serial_No            24178 non-null  int64
 1   Fashion_type         24178 non-null  object
 2   Product_id           24144 non-null  float64
 3   Brand_Name           24144 non-null  object
 4   category             24144 non-null  object
 5   Description          24142 non-null  object
 6   Rating               21947 non-null  float64
 7   Rating_count         21947 non-null  object
 8   Price                24154 non-null  object
 9   MRP_Price            24154 non-null  object
 10  Discount             21283 non-null  object
 11  size                 21319 non-null  object
 12  product_description  24130 non-null  object
 13  image_ref            24142 non-null  object
 14  file_path            24142 non-null  object
 15  image_url            24142 non-null  object
 16  Specifications       24134 non-null  object
 17  Rating_as_stars      20002 non-null  object
dtypes: float64(2), int64(1), object(15)
memory usage: 3.3+ MB

In [7]:
df.describe()

          Serial_No    Product_id        Rating
count  24178.000000  2.414400e+04  21947.000000
mean     745.369385  2.428805e+07      4.170684
std      512.354450  6.038245e+06      0.363585
min        1.000000  1.503240e+05      1.000000
25%      318.000000  2.163112e+07      4.000000
50%      662.000000  2.581962e+07      4.200000
75%     1081.000000  2.914472e+07      4.400000
max     2000.000000  3.096750e+07      5.000000